"""empty message

Revision ID: 4aa549b28f41
Revises: f91eeaf93a9a
Create Date: 2018-01-17 15:57:03.599416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa549b28f41'
down_revision = 'f91eeaf93a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meet', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meet', type_='foreignkey')
    op.drop_column('meet', 'user_id')
    # ### end Alembic commands ###
